schema_version: 1

context:
  name: strongtyping
  version: "3.13.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/FelixTheC/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: de6fb2b7ef4b1c535cc856dd4ea06d17cfa59f86b760de973499a3411d953cf5

build:
  skip: match(python, "<3.13")
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
    - mypy
    - python-librt
  run:
    - python
    - ujson ==5.12.0

tests:
  - python:
      imports:
        - strongtyping
      pip_check: true

about:
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md
  homepage: https://strongtyping.readthedocs.io/en/latest/
  repository: https://github.com/FelixTheC/strongtyping

extra:
  recipe-maintainers:
    - thewchan
