schema_version: 1

context:
  name: strongtyping
  version: "3.13.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/FelixTheC/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 53c31c6a514bdf58f7f60a6d9faf343c844ef68c3f2257ed648f6e7e66faacab

build:
  skip: match(python, "<3.13")
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
    - mypy
    - python-librt
  run:
    - python
    - ujson ==5.12.0

tests:
  - python:
      imports:
        - strongtyping
      pip_check: true

about:
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md
  homepage: https://strongtyping.readthedocs.io/en/latest/
  repository: https://github.com/FelixTheC/strongtyping

extra:
  recipe-maintainers:
    - thewchan
