schema_version: 1

context:
  name: strongtyping
  version: "3.13.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/FelixTheC/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 73804e725ae00ccca1da7dbf44851cd7de0eacae181f26207af993e5f43aceac

build:
  skip: match(python, "<3.13")
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
    - mypy >=1.20.1
    - mypyc >=1.20.1
    - python-librt >=0.10.0
  run:
    - python
    - ujson >=5.12.0
    - python-librt >=0.10.0
    - typing-extensions >=4.4.0

tests:
  - python:
      imports:
        - strongtyping
      pip_check: true

about:
  summary: Decorator which checks whether the function is called with the correct type of parameters
  license: MIT
  license_file: LICENSE.md
  homepage: https://strongtyping.readthedocs.io/en/latest/
  repository: https://github.com/FelixTheC/strongtyping

extra:
  recipe-maintainers:
    - thewchan
